### PR TITLE
Zabbix as default vhost #180

### PR DESCRIPTION
**Pull request by szemlyanoy**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @szemlyanoy 

Thank you for making time to create an PR. 
I can only accept PR that successfully exits the CI tests.

If you would please take a look at it, then I can accept it.

Kind regards,
Werner

**Comment by szemlyanoy** [comment]
Hi @dj-wasabi ,
Please guide me how you usually run CI for zabbix module? Is travis integrated somehow with it? Or should I launch it manually? 
Thanks

**Comment by dj-wasabi** [comment]
Hi @szemlyanoy 

First I see that this PR has conflicts, so even if the tests went fine I could not accept it.
Travis is integrated. When an commit is pushed an travis run will be executed. You can on this page after an push see an link appear to the travis site.

**Comment by szemlyanoy** [comment]
is someone maintaining CI tests? I see lot's of unrelated and odd errors in build trace

**Comment by dj-wasabi** [comment]
Hi,

I don't know why, but for the master branch the travis test is also failing... When running the test locally (at least for the master branch, your branch I haven't tested it) the tests complete successfully.

**Comment by dj-wasabi** [comment]
Thanks!

**Pull request merged**
