### PR TITLE
there is no zabbix proxy package in zbx-3.0

### PR DESCRIPTION
**Pull request by BcTpe4HbIu**

### CODE REVIEW

**Comment by dj-wasabi** [comment]
Hi @BcTpe4HbIu 

Thank you for making time to create an PR. 
I can only accept PR that successfully exits the CI tests.

If you would please take a look at it, then I can accept it.

Kind regards,
Werner

**Comment by BcTpe4HbIu** [comment]
Hi @dj-wasabi 

Sorry, but I don't see how changes from this pull request could cause all this errors in build.

**Comment by dj-wasabi** [comment]
Hi,

I don't know why, but for the master branch the travis test is also failing... When running the test locally (at least for the master branch, your branch I haven't tested it) the tests complete successfully.

**Comment by dj-wasabi** [comment]
Thanks!

**Pull request merged**
