### PR TITLE
Update rspec

### PR DESCRIPTION
**Pull request by bastelfreak**
I'm playing around a bit and updating stuff

* remove much trailing whitespace
* bumped rubocop to latest
* adjusted rubocop conf
* update code to be ruobcop complaint
* add missing facts in spec tests
* use correct scoping in classes
* implement inheritance where needed
* fix tests

### CODE REVIEW

**Comment by bastelfreak** [comment]
I really really like the new HashSyntax in Ruby:
```ruby
{symbol: 'myvalue'}
```

We could enforce this be enabling HashSyntax in rubocop. Any thoughts on this? This isn't valid syntax on anything prior Ruby1.9.3, but the modules doesn't support older versions.

**Comment by bastelfreak** [comment]
w00p w00p almost done \o/

**Comment by bastelfreak** [comment]
we're getting closer

**Comment by bastelfreak** [comment]
Can someone please take a look and review? If anybody wants to adjust the .rubocop.yml: I'm willing to contribute a bit more work, especially in the new HashSyntax, but in a seperate PR.

**Comment by dj-wasabi** [comment]
Hi,

From what I can see this looks very good. @ericsysmin do you want to verify this too before we merge?

**Comment by dj-wasabi** [comment]
Thanks!!!

**Comment by dj-wasabi** [comment]
@bastelfreak 

If you think that updating the '.rubocop.yml' would increase the performance/reliability/maintenance/or ... please be my guest. If you do create new pr for this, I'll wait with creating a new release.

**Pull request merged**
