### PR TITLE
Added support for adding LDAP certificate location to Zabbix Web. Upd…

### PR DESCRIPTION
**Pull request by elricsfate**
…ated documentation to reflect change. NOTE: This change does not enable LDAP. This must be done in the Zabbix GUI. Puppet management of still needs to be implemented

### CODE REVIEW

**Comment by dj-wasabi** [comment]
@elricsfate 

I would like to merge this, but it seems that there are some conflicts. If you could take a look at this that I can merge this request.

Looks very good.

**Comment by elricsfate** [comment]
@dj-wasabi

I'm a bit confused as to why. I made a fork of master, made my changes to the fork, commited/pushed, then made the pull request. 

Is there a way to tell what is conflicting and why? Not sure what could cause it.

**Comment by elricsfate** [comment]
@dj-wasabi 

Hopped on IRC and read some docs. You can now merge this request automatically!
:+1:

**Comment by dj-wasabi** [comment]
Thanks!!

**Pull request merged**
