### PR TITLE
Puppetgem

### PR DESCRIPTION
**Pull request by rnelson0**

### CODE REVIEW

**Comment by rnelson0** [comment]
Fixes #158

**Comment by rnelson0** [comment]
@dj-wasabi I'm working on the Travis CI setup, but it's going to take a while because $rubocop. Can you enable it on the repo? I know it kinda muddies the water to have two changes in one PR but it's the best way I know to make sure this described changed is made effectively :)

**Comment by dj-wasabi** [comment]
Thanks! Think I should create a new version with this PR.

**Comment by rnelson0** [comment]
@dj-wasabi I'm still working out the rspec issues, I'll open a new PR for that. They should probably be resolved before the new version release, though.

**Comment by dj-wasabi** [comment]
Ok, thank you. :+1: 
I'll wait with the next release until a new PR is created.

**Pull request merged**
