### PR TITLE
setting manage_repo to false breaks server install

### PR DESCRIPTION
**Pull request by genebean**
You have this chunk of code in `zabbix::web`

```puppet
# Check if manage_repo is true.
  if $manage_repo {
    if ! defined(Class['zabbix::repo']) {
      class { 'zabbix::repo':
        zabbix_version => $zabbix_version,
      }
    }
  } # END if $manage_repo
```
but nothing that ensures it runs before the this chunk in the same file:

```puppet
default : {
      package { "zabbix-web-${db}":
        ensure  => $zabbix_package_state,
        before  => [
          File['/etc/zabbix/web/zabbix.conf.php'],
          Package['zabbix-web']
        ],
        require => Class['zabbix::repo'],
      }
```

This causes the following error: `Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Package[zabbix-web-mysql] { require => Class[Zabbix::Repo] }, because Class[Zabbix::Repo] doesn't seem to be in the catalog`

I see how to fix this and will be submitting a pull request shortly but wanted to go ahead and list it as a bug in case anyone else is effected by this.

### CODE REVIEW

**Comment by genebean** [comment]
When viewing the changes to `zabbix::repo` it is much easier if you disable showing changes in whitespace.

**Comment by dj-wasabi** [comment]
Thanks! 
Before I approve, did you also look at the rspec tests? They fail on my machine with this pull request. If you don't have experience with it, please tell me than I'll fix it (No worries ;-)). But I need to fix it first before approving this request.

Kind regards,
Werner

**Comment by genebean** [comment]
I've done a little rspec before, what is your test environment? AKA, version of puppet, version of ruby, etc? is `bundle exec rake rspec`  your test command? I added a Travis-CI config file to help with testing to the branch I am working on. Is this what you see test wise too? https://travis-ci.org/genebean/puppet-zabbix

**Comment by genebean** [comment]
it seems you call a file named `spec/spec.opts` in your rspec but that is not in the repo. I am going to manually make one for now just so the tests will run...

**Comment by genebean** [comment]
So, I have gathered that I should call `bundle exec rake spec` to utilize the fixtures but seem to be missing something. Can you share what your testing setup is and, if you have one, your Vagrantfile?

Also, once this is setup the way it needs to be, I'll go back and squash my commits so that only useful ones show up as opposed to having multiple ones where I am hacking on Travis's setup and the like.

**Comment by dj-wasabi** [comment]
Hi Genebean,

At the moment, I'm running the 'rake spec' command locally on my Mac, as I'm developing on the mac. I'am however busy with my internal Jenkins instance to run the 'rake spec' automatically with every push I make. It takes some time though. I was testing with puppet 3.4.3 and ruby 2.0.0 and just upgraded to puppet 3.7.3 on my mac. (And I just noticed with the new puppet I have an error.. :-))

Kind regards,
Werner

**Comment by genebean** [comment]
Thanks. I have a Mac too so I will try it there and see what happens.

**Comment by genebean** [comment]
In the process of looking at this I found in some of my tests that the zabbix-server process is trying to start too soon. I think this can be resolved via commit genebean/puppet-zabbix@1b89db8

As for the tests, I haven't had a chance to try on my Mac but any help you could give would be greatly appreciated.

**Comment by f0** [comment]
+1

**Comment by dj-wasabi** [comment]
Thanks! Will take a look at the rspecs..  no worries ;-)

**Comment by genebean** [comment]
Awesome

**Comment by dj-wasabi** [comment]
Updated the rspec tests, work now. :-)

**Pull request merged**
