### PR TITLE
TLS Support for Zabbix 3.0

### PR DESCRIPTION
**Pull request by ericsysmin**

### CODE REVIEW

**Comment by ericsysmin** [comment]
hopefully this one works

**Comment by ericsysmin** [comment]
@dj-wasabi i think between you and I we could get this one out within a week

**Comment by dj-wasabi** [comment]
Hi @ericsysmin 

Thank you very much for this PR. Will test this PR today.
Looks very good to me.

**Comment by ericsysmin** [comment]
@dj-wasabi no problem, i needed it for work, I should probably remove my old puppet zabbix module from 2014, you took this much farther than I did. I'd love to help contribute more (starting to get this new company I work for to move towards puppet modules from forge)

**Comment by dj-wasabi** [comment]
Thanks!! @ericsysmin 

I'm always open to suggestions/new improvements. (Hint: Windows support ;-))

**Pull request merged**
