### PR TITLE
Update rubocop

### PR DESCRIPTION
**Pull request by bastelfreak**
* remove trailing whitespace

Enabled:
* Style/HashSyntax
* Style/DefWithParentheses

### CODE REVIEW

**Comment by bastelfreak** [comment]
hey. Do we want to keep enabled cops in the .rubocop.yml or should I remove them?

**Comment by bastelfreak** [comment]
puppet-syntax broken: https://github.com/gds-operations/puppet-syntax/issues/51

**Comment by bastelfreak** [comment]
@dj-wasabi what do you think so far, are there any cops that you would like to keep disabled? I think there are ~25 left which I will deal with tomorrow.

I did one commit per cop, which makes reverting them easier if any of them introduces a regression.

**Comment by dj-wasabi** [comment]
Hi @bastelfreak 

This looks very very good. If you could fix the conflicts I'll be very happy to merge this request. :-) :+1:

**Comment by bastelfreak** [comment]
Rubocop doesn't always find all issues related to one cop. It found a few old issues after the rebase. will fix that in a few.

**Comment by bastelfreak** [comment]
I'm ready for merge if this turns green.

**Comment by dj-wasabi** [comment]
Many thanks!

**Pull request merged**
