### PR TITLE
refactoring of repo.pp

### PR DESCRIPTION
**Pull request by bastelfreak**
- use yum variables in repo files ($releasever and $basearch)
- fix $releasever for PSBM
- switch the case for the repos to $::osfamily
- use one repo for all debian like OSes
- use one repo for all RHEL like OSes
- Update sid regex to not exclude jessie ( jessie is now present on the mirror)

### CODE REVIEW

**Comment by bastelfreak** [comment]
This is a approach to fix the issue https://github.com/dj-wasabi/puppet-zabbix/issues/123. This needs to be tested on Xen and aws (with amazon linux).

@dj-wasabi please let me know what you think.

**Comment by bastelfreak** [comment]
I tested this successfully on
* CentOS 7
* [PSBM](http://www.odin.com/de/support/virtualization-suite/psbm/) (RHEL6 Fork)
* [PCS](http://www.odin.com/de/support/virtualization-suite/pcs/) (CloudLinux Fork)
* Debian 8

**Comment by dj-wasabi** [comment]
Hi @bastelfreak 

It looks good, but I can't merge the PR. It has conflicts.
If you fix it, I can merge the PR.

Kind regards,
Werner

**Comment by bastelfreak** [comment]
HI @dj-wasabi, everything green now, branch is mergeable :)

**Comment by dj-wasabi** [comment]
Thanks!

**Pull request merged**
