### PR TITLE
Added Zabbix Proxy, Agent, Server, 3.0 support and Pacemaker exclusions

### PR DESCRIPTION
**Pull request by ericsysmin**

### CODE REVIEW

**Comment by ericsysmin** [comment]
Why isn't this one going through the tests you built? hmmmm, i want to make sure it works on your build

**Comment by dj-wasabi** [comment]
I don't know why, but it is working again .. :-)

**Comment by ericsysmin** [comment]
Yea, just in case I added the same tests to my fork.

**Comment by ericsysmin** [comment]
@dj-wasabi are you working on either proxy 3.0 or agent 3.0? wanted to know which one I should start working on first.

**Comment by dj-wasabi** [comment]
Hi @ericsysmin 
Sorry, I haven't had anytime yet to do something, I try to check this PR at earliest tomorrow and maybe somewhere thursday or friday I'm able to do something with Zabbix 3.0. So if you are able to do this before the end of the week, please do so. :+1: 

It seems that the 2.2.0 an @ericsysmin release is.. :-)
Many thanks!

**Comment by ericsysmin** [comment]
Definitely please check all the functions I've added, I am pretty sure the tests aren't testing everything. I can only test so much on my environments. @dj-wasabi

**Comment by dj-wasabi** [comment]
Thanks!

**Pull request merged**
