### PR TITLE
Update agent.pp

### PR DESCRIPTION
**Pull request by z3rogate**
Listen on OpenVPN Interfaces ...

### CODE REVIEW

**Comment by karolisc** [comment]
+1

**Comment by dj-wasabi** [comment]
What happened?

**Comment by z3rogate** [comment]
@dj-wasabi Sorry for this stupid pull request. I have a Problem with the Listen IP Address of the Agent, i will try to fix it or open an Issue if i'm not skilled enough to fix it.

**Comment by karolisc** [comment]
Why stupid? I use "this" patch for a long time now but never made a pull
request.shame on me :(

**Comment by z3rogate** [comment]
i have open 2 new pull requests ...

https://github.com/dj-wasabi/puppet-zabbix/pull/132
https://github.com/dj-wasabi/puppet-zabbix/pull/133

**Pull request closed without merging**
